USE taverns;
select CONCAT('CREATE TABLE',' ', 'Taverns', ' (')
UNION ALL
select CONCAT(COLUMN_NAME, ' ', DATA_TYPE, ',')
FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Tavern'
AND CHARACTER_MAXIMUM_LENGTH is NULL
UNION
select CONCAT(COLUMN_NAME, ' ', DATA_TYPE, '(', CHARACTER_MAXIMUM_LENGTH, '),')
FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Tavern'
AND CHARACTER_MAXIMUM_LENGTH is NOT NULL
UNION ALL
select (');');



