USE MilesBootCamp;
select CONCAT('CREATE TABLE',' ', 'Taverns', ' (')
UNION ALL
select CONCAT(COLUMN_NAME, ' ', DATA_TYPE, ',')
FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Tavern'
AND CHARACTER_MAXIMUM_LENGTH is NULL
UNION
select CONCAT(COLUMN_NAME, ' ', DATA_TYPE, '(', CHARACTER_MAXIMUM_LENGTH, '),')
FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Tavern'
AND CHARACTER_MAXIMUM_LENGTH is NOT NULL
UNION ALL
select (');');


SELECT
CONCAT('CREATE TABLE ',TABLE_NAME, ' (') as queryPiece
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME = 'Tavern'
UNION ALL
SELECT CONCAT(cols.COLUMN_NAME, ' ', cols.DATA_TYPE,
(CASE WHEN CHARACTER_MAXIMUM_LENGTH IS NOT NULL
Then CONCAT('(', CAST(CHARACTER_MAXIMUM_LENGTH as varchar(100)),
')') Else '' END), ',') as queryPiece FROM
INFORMATION_SCHEMA.COLUMNS as cols WHERE
TABLE_NAME = 'Tavern'
UNION ALL
SELECT ')';
